create extension if not exists pgcrypto with schema extensions;

-- FreqMarks table sync schema for Supabase
-- Default admin key: fpv58
-- SHA-256(fpv58): c415fa767c6a3edc746874be3aa962663421a7db9ed7f1823b07349e72cd90de
-- Default user key: fpv29
-- SHA-256(fpv29): 61b411756a573838426d57b115cf17c08971590118e77da039749604ff035c84

create table if not exists public.page_access (
  id integer primary key default 1 check (id = 1),
  password_hash text,
  admin_key_hash text,
  viewer_key_hash text,
  updated_at timestamptz not null default now()
);

alter table public.page_access add column if not exists password_hash text;
alter table public.page_access add column if not exists admin_key_hash text;
alter table public.page_access add column if not exists viewer_key_hash text;

insert into public.page_access (id, password_hash, admin_key_hash, viewer_key_hash)
values (
  1,
  'c415fa767c6a3edc746874be3aa962663421a7db9ed7f1823b07349e72cd90de',
  'c415fa767c6a3edc746874be3aa962663421a7db9ed7f1823b07349e72cd90de',
  '61b411756a573838426d57b115cf17c08971590118e77da039749604ff035c84'
)
on conflict (id) do nothing;

update public.page_access
set
  password_hash = coalesce(password_hash, admin_key_hash, 'c415fa767c6a3edc746874be3aa962663421a7db9ed7f1823b07349e72cd90de'),
  admin_key_hash = coalesce(admin_key_hash, password_hash, 'c415fa767c6a3edc746874be3aa962663421a7db9ed7f1823b07349e72cd90de'),
  viewer_key_hash = coalesce(viewer_key_hash, '61b411756a573838426d57b115cf17c08971590118e77da039749604ff035c84')
where id = 1;

alter table public.page_access alter column admin_key_hash set not null;
alter table public.page_access alter column viewer_key_hash set not null;

create table if not exists public.app_settings (
  id integer primary key default 1 check (id = 1),
  min_frequency_gap integer not null default 100 check (min_frequency_gap >= 100),
  updated_at timestamptz not null default now()
);

insert into public.app_settings (id, min_frequency_gap)
values (1, 100)
on conflict (id) do nothing;

create table if not exists public.band_channels (
  band_key text not null,
  channel_number integer not null check (channel_number between 1 and 8),
  frequency integer not null check (frequency > 0),
  updated_at timestamptz not null default now(),
  primary key (band_key, channel_number)
);

insert into public.band_channels (band_key, channel_number, frequency)
values
  ('A', 1, 5865), ('A', 2, 5845), ('A', 3, 5825), ('A', 4, 5805), ('A', 5, 5785), ('A', 6, 5765), ('A', 7, 5745), ('A', 8, 5725),
  ('B', 1, 5733), ('B', 2, 5752), ('B', 3, 5771), ('B', 4, 5790), ('B', 5, 5809), ('B', 6, 5828), ('B', 7, 5847), ('B', 8, 5866),
  ('E', 1, 5705), ('E', 2, 5685), ('E', 3, 5665), ('E', 4, 5645), ('E', 5, 5885), ('E', 6, 5905), ('E', 7, 5925), ('E', 8, 5945),
  ('F', 1, 5740), ('F', 2, 5760), ('F', 3, 5780), ('F', 4, 5800), ('F', 5, 5820), ('F', 6, 5840), ('F', 7, 5860), ('F', 8, 5880),
  ('R', 1, 5658), ('R', 2, 5695), ('R', 3, 5732), ('R', 4, 5769), ('R', 5, 5806), ('R', 6, 5843), ('R', 7, 5880), ('R', 8, 5917),
  ('U', 1, 5325), ('U', 2, 5348), ('U', 3, 5366), ('U', 4, 5384), ('U', 5, 5402), ('U', 6, 5420), ('U', 7, 5438), ('U', 8, 5456),
  ('O', 1, 5474), ('O', 2, 5492), ('O', 3, 5510), ('O', 4, 5528), ('O', 5, 5546), ('O', 6, 5564), ('O', 7, 5582), ('O', 8, 5600),
  ('L', 1, 5333), ('L', 2, 5373), ('L', 3, 5413), ('L', 4, 5453), ('L', 5, 5493), ('L', 6, 5533), ('L', 7, 5573), ('L', 8, 5613),
  ('H', 1, 5653), ('H', 2, 5693), ('H', 3, 5733), ('H', 4, 5773), ('H', 5, 5813), ('H', 6, 5853), ('H', 7, 5893), ('H', 8, 5933)
on conflict (band_key, channel_number) do nothing;

create table if not exists public.cell_marks (
  cell_id text primary key,
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  updated_at timestamptz not null default now()
);

create table if not exists public.legend_items (
  color text primary key check (color ~ '^#[0-9A-Fa-f]{6}$'),
  label text not null check (btrim(label) <> ''),
  updated_at timestamptz not null default now()
);

create table if not exists public.legend_models (
  id bigint generated by default as identity primary key,
  color text not null references public.legend_items(color) on delete cascade,
  model_name text not null check (btrim(model_name) <> ''),
  model_number text not null check (btrim(model_number) <> ''),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists legend_models_color_sort_idx
  on public.legend_models (color, sort_order, id);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  title text not null check (btrim(title) <> ''),
  content text not null check (btrim(content) <> ''),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.get_request_header(header_name text)
returns text
language plpgsql
stable
as $$
declare
  headers json;
begin
  begin
    headers := current_setting('request.headers', true)::json;
  exception when others then
    return null;
  end;

  return coalesce(headers ->> lower(header_name), headers ->> header_name);
end;
$$;

create or replace function public.check_access_key(attempt_key text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  attempt_hash text;
  matched_role text;
begin
  attempt_hash := encode(extensions.digest(coalesce(attempt_key, '')::text, 'sha256'::text), 'hex'::text);

  select case
    when attempt_hash = admin_key_hash then 'admin'
    when attempt_hash = viewer_key_hash then 'viewer'
    else null
  end
  into matched_role
  from public.page_access
  where id = 1;

  return matched_role;
end;
$$;

create or replace function public.is_admin_request()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.page_access
    where id = 1
      and admin_key_hash = encode(extensions.digest(coalesce(public.get_request_header('x-freqmarks-access-key'), '')::text, 'sha256'::text), 'hex'::text)
  );
$$;

grant execute on function public.get_request_header(text) to anon;
grant execute on function public.check_access_key(text) to anon;
grant execute on function public.is_admin_request() to anon;

drop trigger if exists page_access_touch_updated_at on public.page_access;
create trigger page_access_touch_updated_at
before update on public.page_access
for each row execute function public.touch_updated_at();

drop trigger if exists app_settings_touch_updated_at on public.app_settings;
create trigger app_settings_touch_updated_at
before update on public.app_settings
for each row execute function public.touch_updated_at();

drop trigger if exists band_channels_touch_updated_at on public.band_channels;
create trigger band_channels_touch_updated_at
before update on public.band_channels
for each row execute function public.touch_updated_at();

drop trigger if exists cell_marks_touch_updated_at on public.cell_marks;
create trigger cell_marks_touch_updated_at
before update on public.cell_marks
for each row execute function public.touch_updated_at();

drop trigger if exists legend_items_touch_updated_at on public.legend_items;
create trigger legend_items_touch_updated_at
before update on public.legend_items
for each row execute function public.touch_updated_at();

drop trigger if exists legend_models_touch_updated_at on public.legend_models;
create trigger legend_models_touch_updated_at
before update on public.legend_models
for each row execute function public.touch_updated_at();

drop trigger if exists notes_touch_updated_at on public.notes;
create trigger notes_touch_updated_at
before update on public.notes
for each row execute function public.touch_updated_at();

alter table public.page_access enable row level security;
alter table public.app_settings enable row level security;
alter table public.band_channels enable row level security;
alter table public.cell_marks enable row level security;
alter table public.legend_items enable row level security;
alter table public.legend_models enable row level security;
alter table public.notes enable row level security;

drop policy if exists "page_access_read_all" on public.page_access;
drop policy if exists "app_settings_read_all" on public.app_settings;
create policy "app_settings_read_all"
on public.app_settings
for select
to anon
using (true);

drop policy if exists "app_settings_insert_all" on public.app_settings;
drop policy if exists "app_settings_admin_insert" on public.app_settings;
create policy "app_settings_admin_insert"
on public.app_settings
for insert
to anon
with check (public.is_admin_request());

drop policy if exists "app_settings_update_all" on public.app_settings;
drop policy if exists "app_settings_admin_update" on public.app_settings;
create policy "app_settings_admin_update"
on public.app_settings
for update
to anon
using (public.is_admin_request())
with check (public.is_admin_request());

drop policy if exists "band_channels_read_all" on public.band_channels;
create policy "band_channels_read_all"
on public.band_channels
for select
to anon
using (true);

drop policy if exists "band_channels_insert_all" on public.band_channels;
drop policy if exists "band_channels_admin_insert" on public.band_channels;
create policy "band_channels_admin_insert"
on public.band_channels
for insert
to anon
with check (public.is_admin_request());

drop policy if exists "band_channels_update_all" on public.band_channels;
drop policy if exists "band_channels_admin_update" on public.band_channels;
create policy "band_channels_admin_update"
on public.band_channels
for update
to anon
using (public.is_admin_request())
with check (public.is_admin_request());

drop policy if exists "cell_marks_read_all" on public.cell_marks;
create policy "cell_marks_read_all"
on public.cell_marks
for select
to anon
using (true);

drop policy if exists "cell_marks_insert_all" on public.cell_marks;
drop policy if exists "cell_marks_admin_insert" on public.cell_marks;
create policy "cell_marks_admin_insert"
on public.cell_marks
for insert
to anon
with check (public.is_admin_request());

drop policy if exists "cell_marks_update_all" on public.cell_marks;
drop policy if exists "cell_marks_admin_update" on public.cell_marks;
create policy "cell_marks_admin_update"
on public.cell_marks
for update
to anon
using (public.is_admin_request())
with check (public.is_admin_request());

drop policy if exists "cell_marks_delete_all" on public.cell_marks;
drop policy if exists "cell_marks_admin_delete" on public.cell_marks;
create policy "cell_marks_admin_delete"
on public.cell_marks
for delete
to anon
using (public.is_admin_request());

drop policy if exists "legend_items_read_all" on public.legend_items;
create policy "legend_items_read_all"
on public.legend_items
for select
to anon
using (true);

drop policy if exists "legend_items_insert_all" on public.legend_items;
drop policy if exists "legend_items_admin_insert" on public.legend_items;
create policy "legend_items_admin_insert"
on public.legend_items
for insert
to anon
with check (public.is_admin_request());

drop policy if exists "legend_items_update_all" on public.legend_items;
drop policy if exists "legend_items_admin_update" on public.legend_items;
create policy "legend_items_admin_update"
on public.legend_items
for update
to anon
using (public.is_admin_request())
with check (public.is_admin_request());

drop policy if exists "legend_items_delete_all" on public.legend_items;
drop policy if exists "legend_items_admin_delete" on public.legend_items;
create policy "legend_items_admin_delete"
on public.legend_items
for delete
to anon
using (public.is_admin_request());

drop policy if exists "legend_models_read_all" on public.legend_models;
create policy "legend_models_read_all"
on public.legend_models
for select
to anon
using (true);

drop policy if exists "legend_models_insert_all" on public.legend_models;
drop policy if exists "legend_models_admin_insert" on public.legend_models;
create policy "legend_models_admin_insert"
on public.legend_models
for insert
to anon
with check (public.is_admin_request());

drop policy if exists "legend_models_update_all" on public.legend_models;
drop policy if exists "legend_models_admin_update" on public.legend_models;
create policy "legend_models_admin_update"
on public.legend_models
for update
to anon
using (public.is_admin_request())
with check (public.is_admin_request());

drop policy if exists "legend_models_delete_all" on public.legend_models;
drop policy if exists "legend_models_admin_delete" on public.legend_models;
create policy "legend_models_admin_delete"
on public.legend_models
for delete
to anon
using (public.is_admin_request());

drop policy if exists "notes_read_all" on public.notes;
create policy "notes_read_all"
on public.notes
for select
to anon
using (true);

drop policy if exists "notes_insert_all" on public.notes;
drop policy if exists "notes_admin_insert" on public.notes;
create policy "notes_admin_insert"
on public.notes
for insert
to anon
with check (public.is_admin_request());

drop policy if exists "notes_update_all" on public.notes;
drop policy if exists "notes_admin_update" on public.notes;
create policy "notes_admin_update"
on public.notes
for update
to anon
using (public.is_admin_request())
with check (public.is_admin_request());

drop policy if exists "notes_delete_all" on public.notes;
drop policy if exists "notes_admin_delete" on public.notes;
create policy "notes_admin_delete"
on public.notes
for delete
to anon
using (public.is_admin_request());

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'band_channels'
  ) then
    alter publication supabase_realtime add table public.band_channels;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'app_settings'
  ) then
    alter publication supabase_realtime add table public.app_settings;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'cell_marks'
  ) then
    alter publication supabase_realtime add table public.cell_marks;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'legend_items'
  ) then
    alter publication supabase_realtime add table public.legend_items;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'legend_models'
  ) then
    alter publication supabase_realtime add table public.legend_models;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notes'
  ) then
    alter publication supabase_realtime add table public.notes;
  end if;
end $$;

-- Optional: change keys later
-- update public.page_access
-- set admin_key_hash = 'PASTE_NEW_ADMIN_SHA256_HASH_HERE',
--     password_hash = 'PASTE_NEW_ADMIN_SHA256_HASH_HERE'
-- where id = 1;
--
-- update public.page_access
-- set viewer_key_hash = 'PASTE_NEW_VIEWER_SHA256_HASH_HERE'
-- where id = 1;
